version: '3'
services:
    app:
        build: .
        links:
            - database
        restart: always
        ports:
            - "5000:5000"
        networks:
            - backend-network
            - frontend-network
        env_file:
            - .env-app

    database:
        image: mysql
        ports:
            - "32000:3306"
        restart: on-failure
        volumes:
            - database-data:/var/lib/mysql
        networks:
            - backend-network
        env_file:
            - .env-docker
volumes:
    database-data:
networks:
    backend-network:
    frontend-network:
