version: '3'
services:
    app:
        build: .
        links:
            - database
        restart: "on-failure"
        ports:
            - "5000:5000"
        networks:
            - backend-network
            - frontend-network
        env_file:
            - app.env

    database:
        image: mysql
        ports:
            - "32000:3306"
        volumes:
            - database-data:/var/lib/mysql
        networks:
            - backend-network
        env_file:
            - docker.env
volumes:
    database-data:
networks:
    backend-network:
    frontend-network:
