"""initial migration

Revision ID: 190021a9ecaf
Revises: 
Create Date: 2020-11-14 17:43:48.584795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190021a9ecaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_email'), 'letters', ['email'], unique=False)
    op.create_index(op.f('ix_letters_timestamp'), 'letters', ['timestamp'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_letters_timestamp'), table_name='letters')
    op.drop_index(op.f('ix_letters_email'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
