"""adding timestap to letter

Revision ID: 61a0ccda0bde
Revises: d93be0f6d402
Create Date: 2020-11-12 13:57:05.563252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a0ccda0bde'
down_revision = 'd93be0f6d402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_letters_timestamp'), 'letters', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_timestamp'), table_name='letters')
    op.drop_column('letters', 'timestamp')
    # ### end Alembic commands ###
