"""adjust conflicting names

Revision ID: d93be0f6d402
Revises: d35937f61493
Create Date: 2020-11-12 13:38:44.242762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd93be0f6d402'
down_revision = 'd35937f61493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_email'), 'letters', ['email'], unique=False)
    op.drop_index('ix_messages_email', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_messages_email', 'messages', ['email'], unique=False)
    op.drop_index(op.f('ix_letters_email'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
